"""initial

Revision ID: 1fc3a9207a75
Revises: 
Create Date: 2023-10-23 18:53:56.430699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc3a9207a75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=15), nullable=False),
    sa.Column('last_name', sa.String(length=15), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email_address'), ['email_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('artwork_url', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artwork_artwork_url'), ['artwork_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_artwork_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artwork_title'))
        batch_op.drop_index(batch_op.f('ix_artwork_price'))
        batch_op.drop_index(batch_op.f('ix_artwork_description'))
        batch_op.drop_index(batch_op.f('ix_artwork_category'))
        batch_op.drop_index(batch_op.f('ix_artwork_artwork_url'))

    op.drop_table('artwork')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email_address'))

    op.drop_table('user')
    # ### end Alembic commands ###
